CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_NETWORKING=y
CONFIG_WIFI=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_NET_L2_WIFI_MGMT=y

CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y

CONFIG_NET_SOCKETS=y
CONFIG_NET_UDP=y

#added for ssd1306
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_DISPLAY=y

CONFIG_CHARACTER_FRAMEBUFFER=y

CONFIG_PINCTRL=y
CONFIG_HEAP_MEM_POOL_SIZE=16384

CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y


